(cl:defpackage sound_package-srv
  (:use )
  (:export
   "PLAYSONG"
   "<PLAYSONG-REQUEST>"
   "PLAYSONG-REQUEST"
   "<PLAYSONG-RESPONSE>"
   "PLAYSONG-RESPONSE"
   "SETVOLUME"
   "<SETVOLUME-REQUEST>"
   "SETVOLUME-REQUEST"
   "<SETVOLUME-RESPONSE>"
   "SETVOLUME-RESPONSE"
   "STOPSONG"
   "<STOPSONG-REQUEST>"
   "STOPSONG-REQUEST"
   "<STOPSONG-RESPONSE>"
   "STOPSONG-RESPONSE"
   "TOGGLEMUTE"
   "<TOGGLEMUTE-REQUEST>"
   "TOGGLEMUTE-REQUEST"
   "<TOGGLEMUTE-RESPONSE>"
   "TOGGLEMUTE-RESPONSE"
  ))

