// Generated by gencpp from file sound_package/PlaySong.msg
// DO NOT EDIT!


#ifndef SOUND_PACKAGE_MESSAGE_PLAYSONG_H
#define SOUND_PACKAGE_MESSAGE_PLAYSONG_H

#include <ros/service_traits.h>


#include <sound_package/PlaySongRequest.h>
#include <sound_package/PlaySongResponse.h>


namespace sound_package
{

struct PlaySong
{

typedef PlaySongRequest Request;
typedef PlaySongResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlaySong
} // namespace sound_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sound_package::PlaySong > {
  static const char* value()
  {
    return "80c5c0485165c4384c0ff23ac3873126";
  }

  static const char* value(const ::sound_package::PlaySong&) { return value(); }
};

template<>
struct DataType< ::sound_package::PlaySong > {
  static const char* value()
  {
    return "sound_package/PlaySong";
  }

  static const char* value(const ::sound_package::PlaySong&) { return value(); }
};


// service_traits::MD5Sum< ::sound_package::PlaySongRequest> should match
// service_traits::MD5Sum< ::sound_package::PlaySong >
template<>
struct MD5Sum< ::sound_package::PlaySongRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sound_package::PlaySong >::value();
  }
  static const char* value(const ::sound_package::PlaySongRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sound_package::PlaySongRequest> should match
// service_traits::DataType< ::sound_package::PlaySong >
template<>
struct DataType< ::sound_package::PlaySongRequest>
{
  static const char* value()
  {
    return DataType< ::sound_package::PlaySong >::value();
  }
  static const char* value(const ::sound_package::PlaySongRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sound_package::PlaySongResponse> should match
// service_traits::MD5Sum< ::sound_package::PlaySong >
template<>
struct MD5Sum< ::sound_package::PlaySongResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sound_package::PlaySong >::value();
  }
  static const char* value(const ::sound_package::PlaySongResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sound_package::PlaySongResponse> should match
// service_traits::DataType< ::sound_package::PlaySong >
template<>
struct DataType< ::sound_package::PlaySongResponse>
{
  static const char* value()
  {
    return DataType< ::sound_package::PlaySong >::value();
  }
  static const char* value(const ::sound_package::PlaySongResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SOUND_PACKAGE_MESSAGE_PLAYSONG_H
