// Generated by gencpp from file sound_package/StopSong.msg
// DO NOT EDIT!


#ifndef SOUND_PACKAGE_MESSAGE_STOPSONG_H
#define SOUND_PACKAGE_MESSAGE_STOPSONG_H

#include <ros/service_traits.h>


#include <sound_package/StopSongRequest.h>
#include <sound_package/StopSongResponse.h>


namespace sound_package
{

struct StopSong
{

typedef StopSongRequest Request;
typedef StopSongResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopSong
} // namespace sound_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sound_package::StopSong > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sound_package::StopSong&) { return value(); }
};

template<>
struct DataType< ::sound_package::StopSong > {
  static const char* value()
  {
    return "sound_package/StopSong";
  }

  static const char* value(const ::sound_package::StopSong&) { return value(); }
};


// service_traits::MD5Sum< ::sound_package::StopSongRequest> should match
// service_traits::MD5Sum< ::sound_package::StopSong >
template<>
struct MD5Sum< ::sound_package::StopSongRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sound_package::StopSong >::value();
  }
  static const char* value(const ::sound_package::StopSongRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sound_package::StopSongRequest> should match
// service_traits::DataType< ::sound_package::StopSong >
template<>
struct DataType< ::sound_package::StopSongRequest>
{
  static const char* value()
  {
    return DataType< ::sound_package::StopSong >::value();
  }
  static const char* value(const ::sound_package::StopSongRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sound_package::StopSongResponse> should match
// service_traits::MD5Sum< ::sound_package::StopSong >
template<>
struct MD5Sum< ::sound_package::StopSongResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sound_package::StopSong >::value();
  }
  static const char* value(const ::sound_package::StopSongResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sound_package::StopSongResponse> should match
// service_traits::DataType< ::sound_package::StopSong >
template<>
struct DataType< ::sound_package::StopSongResponse>
{
  static const char* value()
  {
    return DataType< ::sound_package::StopSong >::value();
  }
  static const char* value(const ::sound_package::StopSongResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SOUND_PACKAGE_MESSAGE_STOPSONG_H
