// Generated by gencpp from file sound_package/ToggleMuteRequest.msg
// DO NOT EDIT!


#ifndef SOUND_PACKAGE_MESSAGE_TOGGLEMUTEREQUEST_H
#define SOUND_PACKAGE_MESSAGE_TOGGLEMUTEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sound_package
{
template <class ContainerAllocator>
struct ToggleMuteRequest_
{
  typedef ToggleMuteRequest_<ContainerAllocator> Type;

  ToggleMuteRequest_()
    {
    }
  ToggleMuteRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::sound_package::ToggleMuteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sound_package::ToggleMuteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleMuteRequest_

typedef ::sound_package::ToggleMuteRequest_<std::allocator<void> > ToggleMuteRequest;

typedef boost::shared_ptr< ::sound_package::ToggleMuteRequest > ToggleMuteRequestPtr;
typedef boost::shared_ptr< ::sound_package::ToggleMuteRequest const> ToggleMuteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sound_package::ToggleMuteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sound_package::ToggleMuteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace sound_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sound_package::ToggleMuteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sound_package::ToggleMuteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sound_package::ToggleMuteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sound_package::ToggleMuteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sound_package::ToggleMuteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sound_package::ToggleMuteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sound_package::ToggleMuteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sound_package::ToggleMuteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::sound_package::ToggleMuteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sound_package/ToggleMuteRequest";
  }

  static const char* value(const ::sound_package::ToggleMuteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sound_package::ToggleMuteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# No request message needed\n"
"\n"
"# Response message format\n"
;
  }

  static const char* value(const ::sound_package::ToggleMuteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sound_package::ToggleMuteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleMuteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sound_package::ToggleMuteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::sound_package::ToggleMuteRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SOUND_PACKAGE_MESSAGE_TOGGLEMUTEREQUEST_H
