// Generated by gencpp from file sound_package/ToggleMute.msg
// DO NOT EDIT!


#ifndef SOUND_PACKAGE_MESSAGE_TOGGLEMUTE_H
#define SOUND_PACKAGE_MESSAGE_TOGGLEMUTE_H

#include <ros/service_traits.h>


#include <sound_package/ToggleMuteRequest.h>
#include <sound_package/ToggleMuteResponse.h>


namespace sound_package
{

struct ToggleMute
{

typedef ToggleMuteRequest Request;
typedef ToggleMuteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleMute
} // namespace sound_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sound_package::ToggleMute > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sound_package::ToggleMute&) { return value(); }
};

template<>
struct DataType< ::sound_package::ToggleMute > {
  static const char* value()
  {
    return "sound_package/ToggleMute";
  }

  static const char* value(const ::sound_package::ToggleMute&) { return value(); }
};


// service_traits::MD5Sum< ::sound_package::ToggleMuteRequest> should match
// service_traits::MD5Sum< ::sound_package::ToggleMute >
template<>
struct MD5Sum< ::sound_package::ToggleMuteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sound_package::ToggleMute >::value();
  }
  static const char* value(const ::sound_package::ToggleMuteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sound_package::ToggleMuteRequest> should match
// service_traits::DataType< ::sound_package::ToggleMute >
template<>
struct DataType< ::sound_package::ToggleMuteRequest>
{
  static const char* value()
  {
    return DataType< ::sound_package::ToggleMute >::value();
  }
  static const char* value(const ::sound_package::ToggleMuteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sound_package::ToggleMuteResponse> should match
// service_traits::MD5Sum< ::sound_package::ToggleMute >
template<>
struct MD5Sum< ::sound_package::ToggleMuteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sound_package::ToggleMute >::value();
  }
  static const char* value(const ::sound_package::ToggleMuteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sound_package::ToggleMuteResponse> should match
// service_traits::DataType< ::sound_package::ToggleMute >
template<>
struct DataType< ::sound_package::ToggleMuteResponse>
{
  static const char* value()
  {
    return DataType< ::sound_package::ToggleMute >::value();
  }
  static const char* value(const ::sound_package::ToggleMuteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SOUND_PACKAGE_MESSAGE_TOGGLEMUTE_H
